W7D5/reddit_clone_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #routes for users and nested subs/new subs/create
  resources :users do
    resources :subs, only: [:new, :create]
  end

  #route for session
  resource :session, only: [:new, :create, :destroy]

  #routes for subs and nested posts/new posts/create
  resources :subs, only: [:index, :show, :edit, :update] do 
    resources :posts, only: [:new, :create]
  end

  #routes for posts
  resources :posts, only: [:show, :edit, :update, :destroy]
end

W7D5/reddit_clone_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditCloneApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>
    <a href="<%= users_url %>">All Users Page</a>
    <a href="<%= subs_url %>">All Subforums Page</a>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="POST">
        <p>Logged in as: <%= current_user.username %></p>
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Log Out">
      </form>
    <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
      <a href="<%= new_session_url %>">Sign In</a>
    <% end %>
    <%= yield %>
  </body>
</html>