W7D5/reddit_clone_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #routes for users and nested subs/new subs/create
  resources :users do
    resources :subs, only: [:new, :create]
  end

  #route for session
  resource :session, only: [:new, :create, :destroy]

  #routes for subs and nested posts/new posts/create
  resources :subs, only: [:index, :show, :edit, :update] do 
    resources :posts, only: [:new, :create]
  end

  #routes for posts
  resources :posts, only: [:show, :edit, :update, :destroy]
end

W7D5/reddit_clone_app/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
  validates :description, null: false
  validates :moderator_id, uniqueness: { scope: :title }

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User
  
  has_many :posts,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Post,
    dependent: :destroy
end

W7D5/reddit_clone_app/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only: [:edit, :udpate, :destroy]

  def show
    @sub = Sub.find(params[:id])
    @posts = Post.all.select { |post| post.sub_id == @sub.id }
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    @user = User.find(params[:user_id])
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = params[:sub][:moderator_id]
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.update(title: params[:sub][:title], description: params[:sub][:description], moderator_id: params[:sub][:moderator_id])
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

W7D5/reddit_clone_app/app/helpers/subs_helper.rb
module SubsHelper
end

W7D5/reddit_clone_app/app/views/subs/edit.html.erb
<h1>Edit subforum</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label>Title: 
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description: 
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <input type="hidden" name="sub[moderator_id]" value="<%= @sub.moderator_id %>">
  <input type="submit" value="Edit subforum">
</form>
<a href="<%= sub_url(@sub) %>">Cancel</a>

W7D5/reddit_clone_app/app/views/subs/index.html.erb
<h1>All Sub-Forums</h1>

<a href="<%= new_user_sub_url(current_user.id) %>">Create a subforum</a>

<% @subs.each do |sub| %>
  <ul>
    <li>Moderator: <%= User.find_by(id: sub.moderator_id).username %></li>
    <li>Title: <%= sub.title %></li>
    <li>Description: <%= sub.description %></li>
    <li><a href="<%= sub_url(sub) %>">View subforum</a></li>
  </ul>
<% end %>

W7D5/reddit_clone_app/app/views/subs/new.html.erb
<h1>Create a Sub-Forum</h1>

<form action="<%= user_subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title: 
    <input type="text" name="sub[title]">
  </label>
  <label>Description: 
    <input type="text" name="sub[description]">
  </label>
  <input type="hidden" name="sub[moderator_id]" value="<%= params[:user_id] %>">
  <input type="submit" value="Create subforum">
</form>

W7D5/reddit_clone_app/app/views/subs/show.html.erb
<h1>View Sub-Forum</h1>

<a href="<%= subs_url %>">View all subforums</a>

<h4>Subforum details</h4>
<ul>
  <li>Moderator: <%= User.find_by(id: @sub.moderator_id).username %></li>
  <li>Title: <%= @sub.title %></li>
  <li>Description: <%= @sub.description %></li>
  <% if is_moderator? %>
    <li><a href="<%= edit_sub_url(@sub) %>">Edit subforum</a></li>
  <% end %>
  <li><a href="<%= new_sub_post_url(@sub) %>">Create a Post</a></li>
</ul>

<h4>All subforum posts</h4>
<ul>
  <% if @posts %>
    <% @posts.each do |post| %>
      <li><%= post.title %></li>
      <a href="<%= post_url(post) %>">View Post</a>
    <% end %>
  <% end %>
</ul>